CREATE TABLE IF NOT EXISTS tb_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    reservation_date TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_reservation_customer FOREIGN KEY (customer_id) REFERENCES tb_customers(id),
    CONSTRAINT fk_reservation_book FOREIGN KEY (book_id) REFERENCES tb_books(id)
);

